"""Generate synthetic interoperability fixtures with Pillow, tifffile and zlib.

Run in a development environment with pillow, numpy and tifffile installed.
The resulting Dart file is portable to both native and browser tests.
"""
import base64
import io
from pathlib import Path
import struct
import zlib

import numpy as np
from PIL import Image, ImageCms
import tifffile

fixtures = {}
rgba = np.array([[[0, 1, 127, 0], [30, 60, 90, 128]], [[255, 250, 240, 255], [99, 66, 33, 64]]], dtype=np.uint8)
profile = ImageCms.ImageCmsProfile(ImageCms.createProfile('sRGB')).tobytes()

def save_pillow(name, image, format, **options):
    output = io.BytesIO()
    image.save(output, format=format, **options)
    fixtures[name] = output.getvalue()

save_pillow('progressiveJpeg', Image.fromarray(rgba[:, :, :3]), 'JPEG', progressive=True, quality=95, icc_profile=profile)
save_pillow('cmykJpeg', Image.new('CMYK', (2, 2), (0, 255, 255, 0)), 'JPEG', quality=100)
palette = Image.new('P', (2, 2))
palette.putpalette([255, 0, 0, 0, 255, 0, 0, 0, 255] + [0] * 759)
palette.putdata([0, 1, 2, 1])
save_pillow('palettePng', palette, 'PNG', transparency=bytes([0, 128, 255]))

def chunk(kind, data):
    return struct.pack('>I', len(data)) + kind + data + struct.pack('>I', zlib.crc32(kind + data))

# An independent PNG writer keeps all sixteen bits; include Adam7 coverage.
rgba16 = rgba.astype(np.uint16) * 257
rgba16[0, 1] = [12345, 23456, 34567, 45678]
for interlaced in [False, True]:
    raw = bytearray()
    passes = [(0, 0, 1, 1)] if not interlaced else [(0, 0, 8, 8), (4, 0, 8, 8), (0, 4, 4, 8), (2, 0, 4, 4), (0, 2, 2, 4), (1, 0, 2, 2), (0, 1, 1, 2)]
    for x, y, dx, dy in passes:
        for row in rgba16[y::dy, x::dx]:
            if len(row):
                raw.append(0)
                raw.extend(row.astype('>u2').tobytes())
    fixtures['interlacedPng16' if interlaced else 'png16'] = (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', 2, 2, 16, 6, 0, 0, int(interlaced))) + chunk(b'iCCP', b'sRGB\0\0' + zlib.compress(profile)) + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'eXIf', b'II*\0\x08\0\0\0\0\0\0\0\0\0') + chunk(b'IEND', b''))

for name, pixels, options in [
    ('tiff16', rgba16, {}),
    ('tiff16BigEndian', rgba16, dict(byteorder='>')),
    ('tiff16Tiled', rgba16, dict(tile=(16, 16))),
    ('tiff16Planar', rgba16.transpose(2, 0, 1), dict(planarconfig='separate')),
    ('tiffFloat', np.array([[[1.5, -0.25, 0.5, 1.0], [0.125, 0.25, 0.75, 0.5]]], dtype=np.float32), {}),
    ('bigTiff', rgba, dict(bigtiff=True)),
]:
    output = io.BytesIO()
    tifffile.imwrite(output, pixels, photometric='rgb', extrasamples=['unassalpha'], metadata=None, iccprofile=profile, **options)
    fixtures[name] = output.getvalue()
for orientation in range(1, 9):
    output = io.BytesIO()
    tifffile.imwrite(output, rgba[:1], photometric='rgb', extrasamples=['unassalpha'], metadata=None, extratags=[(274, 'H', 1, orientation, False)])
    fixtures[f'tiffOrientation{orientation}'] = output.getvalue()

lines = ["import 'dart:convert';", "import 'dart:typed_data';", '', '/// Original synthetic files generated by tool/raster_fixture_generator.py.', 'Uint8List rasterFixture(String name) => base64Decode(_fixtures[name]!);', '', 'const Map<String, String> _fixtures = {']
for name, data in fixtures.items():
    encoded = base64.b64encode(data).decode()
    lines.append(f"  '{name}':")
    for position in range(0, len(encoded), 100):
        lines.append("      '" + encoded[position:position + 100] + ("'," if position + 100 >= len(encoded) else "'"))
lines.append('};')
Path('test/raster_fixtures.dart').write_text('\n'.join(lines) + '\n')
print(f'Generated {len(fixtures)} raster fixtures.')
